### ISSUE TITLE
Bootstrap 4?

### ISSUE THREAD

**Issue by AmirGilboa** [third774/ng-bootstrap-form-validation#33]
Any chance to support bootstrap 4.x ?
I know we discussed this in the past, and there was no thrill to do so, but time has passed, and i see more and  more systems moving to bootstrap 4, that has different error classes (see below).
I would love to do a pr, but have no clue were to start. give me some clues, and i will jump in.
hopefully it is just changing the class names? thanks.
Here is a sample of how validation should be in bootstrap 4:

```
<div class="form-group has-danger">
    <label class="form-control-label">Username</label>
    <input type="text" class="form-control is-invalid">
    <div class="invalid-feedback">Sorry, that username's taken. Try another?</div>
</div>
```

**Comment by third774** [comment]
Sure! You should be able to pull down the repo and just run `npm i && npm start` to get started.

The API for setting this up should look something like this:
```ts
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule , ReactiveFormsModule} from '@angular/forms';
import { AppComponent } from './app.component';

import { NgBootstrapFormValidationModule, BootstrapVersion } from 'ng-bootstrap-form-validation';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    ReactiveFormsModule,
    NgBootstrapFormValidationModule.forRoot({bootstrapVersion: BootstrapVersion.Four})
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {
}
```

The classes that get applied are in `MessagesComponent`. The version should be fed into the `ErrorMessageService` and then injected into the `MessagesComponent`.

The only problem is, we're going to need to also make a breaking API change to the `forRoot()` method, which will take a config object with a `customErrorMessages` key on it, along with the new version key described above.

Feel free to give it a go and open a PR.

Otherwise, I'll try to get something put together and released in the near future.

**Comment by ijavid** [comment]
+1 for Bootstrap 4 support

**Comment by maximepvrt** [comment]
@third774 can you publish a prerelease on npm ?
