### ISSUE TITLE
How to validate confirm password field.

### ISSUE THREAD

**Issue by ultimateakash** [third774/ng-bootstrap-form-validation#53]
this.formGroup = new FormGroup({
      name: new FormControl('', [
        Validators.required
      ]),
      phone: new FormControl('', [
        Validators.required,
        Validators.minLength(8),
        Validators.maxLength(10)
      ]),
      email: new FormControl('', [
        Validators.required,
        Validators.pattern(/^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/)
      ]),
      password: new FormControl('', [
        Validators.required,
        Validators.minLength(8),
        Validators.maxLength(20)
      ]),
      cpassword: new FormControl('', [
        Validators.required,
        Validators.minLength(8),
        Validators.maxLength(20)
      ])
    });

Please help me. thanks.

**Comment by third774** [comment]
Closing since this is more of a general Angular question. Here's a guide that might help. Once you have this validation in place, you should be able to generate an error with the [custom error messages](https://github.com/third774/ng-bootstrap-form-validation#custom-error-messages).

https://scotch.io/@ibrahimalsurkhi/match-password-validation-with-angular-2
